Repository w3c/wot-marketing, pull requests merged in 2021-04, with the labels that each got.

#117 add blog proposal for video
  proposals/blogProposal.md
Labels: major

#160 Fixes Issue 153
  docs/ig/index.html
  docs/wg/index.html
Labels: Webpage

#154 add PPTX with some figures
  material/wot-figures.pptx
Labels: minor

#165 Add Japanese captions for the WoT Explainer Video
  videos/WoT-Explainer-Video/WOTMotion.ja.vtt
Labels: minor

#166 Update WOTMotion.en.vtt
  videos/WoT-Explainer-Video/WOTMotion.en.vtt
Labels: bug

#168 Fix the starting time of the entry 10 in WOTMotion.it.vtt
  videos/WoT-Explainer-Video/WOTMotion.it.vtt
Labels: bug

#169 Fix the starting time of the entry 10 in WOTMotion.zh-Hans.vtt
  videos/WoT-Explainer-Video/WOTMotion.zh-Hans.vtt
Labels: bug

#170 Fix the starting time of the entry 10 in WOTMotion.de.vtt
  videos/WoT-Explainer-Video/WOTMotion.de.vtt
Labels: bug

#171 Fix the starting time of the entry 10 in WOTMotion.fr.vtt
  videos/WoT-Explainer-Video/WOTMotion.fr.vtt
Labels: bug

#162 Liaison - Issue 161
  docs/ig/index.html
Labels: Webpage
